# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magiclink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magictoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
